[package]
name = "foco-spike"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.36.1"
serde_json = "1.0.151"
winit = { version = "0.30", default-features = false }
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = ["NSApplication", "NSResponder", "NSWindow", "NSGraphics"] }
objc2-core-foundation = "0.3"
objc2-core-graphics = "0.3"
objc2-foundation = { version = "0.3", features = ["NSArray", "NSDictionary", "NSString", "NSValue"] }

[profile.dev]
opt-level = 1
