[package]
name = "n-vistas"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.36.1"
resvg = "0.45"
winit = { version = "0.30", default-features = false }
image = { version = "0.25", default-features = false, features = ["png"] }
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = ["NSApplication", "NSResponder", "NSRunningApplication"] }

[profile.dev]
opt-level = 1
