quadrantChart
  title Cuadrantes
  x-axis Bajo --> Alto
  y-axis Poco --> Mucho
  quadrant-1 Cuadranteuno
  quadrant-2 Cuadrantedos
  quadrant-3 Cuadrantetres
  quadrant-4 Cuadrantecuatro
  Puntouno: [0.3, 0.6]
